workflows:
  android-debug-apk:
    name: Android Debug APK
    max_build_duration: 120
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get dependencies
        script: |
          cd reminder_demo
          flutter pub get
      - name: Build debug APK
        script: |
          cd reminder_demo
          flutter build apk --debug --android-skip-build-dependency-validation
    artifacts:
      - reminder_demo/build/app/outputs/flutter-apk/app-debug.apk